[project]
name = "gp2040ce-binary-tools"
version = "0"
description = "Tools for working with GP2040-CE binary dumps."
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "Brian S. Stephan", email = "bss@incorporeal.org"},
]
requires-python = ">=3.8"
dependencies = ["grpcio-tools"]

[project.optional-dependencies]
dev = ["flake8", "flake8-blind-except", "flake8-builtins", "flake8-docstrings", "flake8-executable", "flake8-fixme",
       "flake8-isort", "flake8-logging-format", "flake8-mutable", "flake8-pyproject", "pip-tools"]

[project.scripts]
visualize-storage = "gp2040ce_bintools.storage:visualize"

[tool.flake8]
max-line-length = 120
